// Generated by https://quicktype.io

export interface LoginResponse {
  usuario: User;
  token: string;
}

export interface User {
  rol: string;
  estado: boolean;
  google: boolean;
  nombre: string;
  correo: string;
  uid: string;
}

export interface LoginData {
  correo: string;
  password: string;
}

export interface SignupData extends LoginData {
  nombre: string;
}

export type AuthStatus = 'checking' | 'authenticated' | 'non-authenticated';

// Generated by https://quicktype.io

export interface ProductsResponse {
  total: number;
  productos: Product[];
}

export interface Category {
  _id: string;
  nombre: string;
}

export interface CategoryUser {
  _id: string;
  nombre: string;
}

export interface Product {
  _id: string;
  precio: number;
  nombre: string;
  categoria: Category;
  usuario: CategoryUser;
  img: string;
}
